/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.gtd;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AttacksPerCountry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AttacksPerCountry\",\"namespace\":\"org.gtd\",\"fields\":[{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"count\",\"type\":\"int\"},{\"name\":\"attackDetails\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AttackDetails\",\"fields\":[{\"name\":\"location\",\"type\":{\"type\":\"record\",\"name\":\"Location\",\"fields\":[{\"name\":\"region\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"lattitude\",\"type\":\"string\"},{\"name\":\"longitude\",\"type\":\"string\"}]}},{\"name\":\"time\",\"type\":{\"type\":\"record\",\"name\":\"Time\",\"fields\":[{\"name\":\"year\",\"type\":\"string\"},{\"name\":\"month\",\"type\":\"string\"},{\"name\":\"dt\",\"type\":\"string\"}]}},{\"name\":\"attack\",\"type\":{\"type\":\"record\",\"name\":\"Attack\",\"fields\":[{\"name\":\"suicide\",\"type\":\"boolean\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"motive\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"weapon\",\"type\":[\"null\",\"string\"],\"default\":null}]}},{\"name\":\"target\",\"type\":{\"type\":\"record\",\"name\":\"Target\",\"fields\":[{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"subType\",\"type\":\"string\"},{\"name\":\"corp\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"target1\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"nationality1\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"target2\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"nationality2\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"target3\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"nationality3\",\"type\":[\"null\",\"string\"],\"default\":null}]}}]}}}]}");
  @Deprecated public java.lang.CharSequence country;
  @Deprecated public int count;
  @Deprecated public java.util.List<org.gtd.AttackDetails> attackDetails;

  /**
   * Default constructor.
   */
  public AttacksPerCountry() {}

  /**
   * All-args constructor.
   */
  public AttacksPerCountry(java.lang.CharSequence country, java.lang.Integer count, java.util.List<org.gtd.AttackDetails> attackDetails) {
    this.country = country;
    this.count = count;
    this.attackDetails = attackDetails;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return country;
    case 1: return count;
    case 2: return attackDetails;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: country = (java.lang.CharSequence)value$; break;
    case 1: count = (java.lang.Integer)value$; break;
    case 2: attackDetails = (java.util.List<org.gtd.AttackDetails>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }

  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'count' field.
   */
  public java.lang.Integer getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(java.lang.Integer value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'attackDetails' field.
   */
  public java.util.List<org.gtd.AttackDetails> getAttackDetails() {
    return attackDetails;
  }

  /**
   * Sets the value of the 'attackDetails' field.
   * @param value the value to set.
   */
  public void setAttackDetails(java.util.List<org.gtd.AttackDetails> value) {
    this.attackDetails = value;
  }

  /** Creates a new AttacksPerCountry RecordBuilder */
  public static org.gtd.AttacksPerCountry.Builder newBuilder() {
    return new org.gtd.AttacksPerCountry.Builder();
  }
  
  /** Creates a new AttacksPerCountry RecordBuilder by copying an existing Builder */
  public static org.gtd.AttacksPerCountry.Builder newBuilder(org.gtd.AttacksPerCountry.Builder other) {
    return new org.gtd.AttacksPerCountry.Builder(other);
  }
  
  /** Creates a new AttacksPerCountry RecordBuilder by copying an existing AttacksPerCountry instance */
  public static org.gtd.AttacksPerCountry.Builder newBuilder(org.gtd.AttacksPerCountry other) {
    return new org.gtd.AttacksPerCountry.Builder(other);
  }
  
  /**
   * RecordBuilder for AttacksPerCountry instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AttacksPerCountry>
    implements org.apache.avro.data.RecordBuilder<AttacksPerCountry> {

    private java.lang.CharSequence country;
    private int count;
    private java.util.List<org.gtd.AttackDetails> attackDetails;

    /** Creates a new Builder */
    private Builder() {
      super(org.gtd.AttacksPerCountry.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.gtd.AttacksPerCountry.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing AttacksPerCountry instance */
    private Builder(org.gtd.AttacksPerCountry other) {
            super(org.gtd.AttacksPerCountry.SCHEMA$);
      if (isValidValue(fields()[0], other.country)) {
        this.country = data().deepCopy(fields()[0].schema(), other.country);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.count)) {
        this.count = data().deepCopy(fields()[1].schema(), other.count);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.attackDetails)) {
        this.attackDetails = data().deepCopy(fields()[2].schema(), other.attackDetails);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'country' field */
    public java.lang.CharSequence getCountry() {
      return country;
    }
    
    /** Sets the value of the 'country' field */
    public org.gtd.AttacksPerCountry.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.country = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'country' field has been set */
    public boolean hasCountry() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'country' field */
    public org.gtd.AttacksPerCountry.Builder clearCountry() {
      country = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'count' field */
    public java.lang.Integer getCount() {
      return count;
    }
    
    /** Sets the value of the 'count' field */
    public org.gtd.AttacksPerCountry.Builder setCount(int value) {
      validate(fields()[1], value);
      this.count = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'count' field has been set */
    public boolean hasCount() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'count' field */
    public org.gtd.AttacksPerCountry.Builder clearCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'attackDetails' field */
    public java.util.List<org.gtd.AttackDetails> getAttackDetails() {
      return attackDetails;
    }
    
    /** Sets the value of the 'attackDetails' field */
    public org.gtd.AttacksPerCountry.Builder setAttackDetails(java.util.List<org.gtd.AttackDetails> value) {
      validate(fields()[2], value);
      this.attackDetails = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'attackDetails' field has been set */
    public boolean hasAttackDetails() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'attackDetails' field */
    public org.gtd.AttacksPerCountry.Builder clearAttackDetails() {
      attackDetails = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public AttacksPerCountry build() {
      try {
        AttacksPerCountry record = new AttacksPerCountry();
        record.country = fieldSetFlags()[0] ? this.country : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.count = fieldSetFlags()[1] ? this.count : (java.lang.Integer) defaultValue(fields()[1]);
        record.attackDetails = fieldSetFlags()[2] ? this.attackDetails : (java.util.List<org.gtd.AttackDetails>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
